"""Stable event names for Authorization Technical Logging v1."""

SESSION_CREATED = "auth.session_created"
SESSION_REUSED = "auth.session_reused"
WORKER_STARTED = "auth.worker_started"
INITIAL_DELAY_COMPLETED = "auth.initial_delay_completed"
CLIENT_CHECK = "auth.client_check"
CLIENT_READY = "auth.client_ready"
FALLBACK_TRIGGERED = "auth.fallback_triggered"
AUTHORIZATION_REQUEST = "auth.authorization_request"
AUTHORIZATION_RESPONSE = "auth.authorization_response"
VERIFICATION_STARTED = "auth.verification_started"
VERIFICATION_RESULT = "auth.verification_result"
RETRY_SCHEDULED = "auth.retry_scheduled"
OMADA_UNAVAILABLE = "auth.omada_unavailable"
TOKEN_ERROR = "auth.token_error"
SESSION_FINISHED = "auth.session_finished"
WORKER_COMPLETED = "auth.worker_completed"
WORKER_EXCEPTION = "auth.worker_exception"

CAPPORT_API_REQUEST = "capport.api_request"
CAPPORT_CLIENT_RESOLVED = "capport.client_resolved"
CAPPORT_CLIENT_NOT_FOUND = "capport.client_not_found"
CAPPORT_LOOKUP_FAILED = "capport.lookup_failed"
CAPPORT_DETAIL_LOOKUP_FALLBACK = "capport.detail_lookup_fallback"
CAPPORT_STATE_RESPONSE = "capport.state_response"
CAPPORT_PORTAL_OPENED = "capport.portal_opened"
