"""
Application configuration defaults.

This module stores default values for the application.
"""

import os

# Server settings
HOST = "127.0.0.1"
PORT = 8088

# Debug mode
DEBUG = False

# SSL verification
VERIFY_SSL = False

# Logging level
LOG_LEVEL = "INFO"

# Public Portal Open Counter
PORTAL_COUNTER_ENABLED = True
PORTAL_COUNTER_DB_PATH = "/opt/CaptivePortal/data/portal_counter.db"
PORTAL_COUNTER_TIMEZONE = "Asia/Baku"
PORTAL_COUNTER_API_ENABLED = True

# Public completed-session traffic counter
PUBLIC_TRAFFIC_COUNTER_ENABLED = os.getenv(
    "PUBLIC_TRAFFIC_COUNTER_ENABLED",
    "true",
)
PUBLIC_TRAFFIC_SSID = os.getenv(
    "PUBLIC_TRAFFIC_SSID",
    "Zefer_Parki",
)
PUBLIC_TRAFFIC_DB_PATH = os.getenv(
    "PUBLIC_TRAFFIC_DB_PATH",
    "/opt/CaptivePortal/data/public_traffic.sqlite3",
)
PUBLIC_TRAFFIC_SCAN_INTERVAL_SECONDS = os.getenv(
    "PUBLIC_TRAFFIC_SCAN_INTERVAL_SECONDS",
    "10",
)
PUBLIC_TRAFFIC_FRONTEND_REFRESH_SECONDS = os.getenv(
    "PUBLIC_TRAFFIC_FRONTEND_REFRESH_SECONDS",
    "60",
)

# Authorization Technical Logging
AUTH_TELEMETRY_ENABLED = True
AUTH_TELEMETRY_LOG_PATH = "/opt/CaptivePortal/logs/auth_telemetry.log"
AUTH_TELEMETRY_LEVEL = "INFO"
AUTH_TELEMETRY_SCHEMA_VERSION = 1
AUTH_TELEMETRY_ROTATION_MAX_BYTES = 52428800
AUTH_TELEMETRY_ROTATION_BACKUP_COUNT = 10

# Authorized Client Snapshot Collector (safe disabled default)
VISITOR_SNAPSHOT_ENABLED = os.getenv(
    "VISITOR_SNAPSHOT_ENABLED",
    "false",
)
VISITOR_SNAPSHOT_LOG_FILE = os.getenv(
    "VISITOR_SNAPSHOT_LOG_FILE",
    "/opt/CaptivePortal/logs/visitor_snapshots.log",
)
VISITOR_SNAPSHOT_MAX_WORKERS = os.getenv(
    "VISITOR_SNAPSHOT_MAX_WORKERS",
    "2",
)
VISITOR_SNAPSHOT_MAX_PENDING = os.getenv(
    "VISITOR_SNAPSHOT_MAX_PENDING",
    "100",
)
VISITOR_SNAPSHOT_MAX_JOB_AGE_SECONDS = os.getenv(
    "VISITOR_SNAPSHOT_MAX_JOB_AGE_SECONDS",
    "30",
)
VISITOR_SNAPSHOT_REQUEST_TIMEOUT_SECONDS = os.getenv(
    "VISITOR_SNAPSHOT_REQUEST_TIMEOUT_SECONDS",
    "5",
)
VISITOR_SNAPSHOT_RETRY_DELAYS_SECONDS = os.getenv(
    "VISITOR_SNAPSHOT_RETRY_DELAYS_SECONDS",
    "2,5",
)
VISITOR_SNAPSHOT_ROTATION_MAX_BYTES = os.getenv(
    "VISITOR_SNAPSHOT_ROTATION_MAX_BYTES",
    "52428800",
)
VISITOR_SNAPSHOT_ROTATION_BACKUP_COUNT = os.getenv(
    "VISITOR_SNAPSHOT_ROTATION_BACKUP_COUNT",
    "20",
)
VISITOR_SNAPSHOT_SHUTDOWN_TIMEOUT_SECONDS = os.getenv(
    "VISITOR_SNAPSHOT_SHUTDOWN_TIMEOUT_SECONDS",
    "90",
)

# Visitor Device Registry
#
# Disabled until a separate production activation is approved.
VISITOR_REGISTRY_ENABLED = os.getenv(
    "VISITOR_REGISTRY_ENABLED",
    "false",
)
VISITOR_REGISTRY_DB_PATH = os.getenv(
    "VISITOR_REGISTRY_DB_PATH",
    "/opt/CaptivePortal/data/visitor_registry.sqlite3",
)
VISITOR_REGISTRY_SCAN_INTERVAL_SECONDS = os.getenv(
    "VISITOR_REGISTRY_SCAN_INTERVAL_SECONDS",
    "5",
)
VISITOR_REGISTRY_SHUTDOWN_TIMEOUT_SECONDS = os.getenv(
    "VISITOR_REGISTRY_SHUTDOWN_TIMEOUT_SECONDS",
    "10",
)
VISITOR_REGISTRY_MAX_LINE_BYTES = os.getenv(
    "VISITOR_REGISTRY_MAX_LINE_BYTES",
    "4194304",
)

# Visit Lifecycle v1 (safe disabled default)
VISIT_LIFECYCLE_ENABLED = os.getenv(
    "VISIT_LIFECYCLE_ENABLED", "false"
)
VISIT_LIFECYCLE_DB_PATH = os.getenv(
    "VISIT_LIFECYCLE_DB_PATH",
    "/opt/CaptivePortal/data/visits.sqlite3",
)
VISIT_LIFECYCLE_WEBHOOK_SOURCE = os.getenv(
    "VISIT_LIFECYCLE_WEBHOOK_SOURCE",
    "/opt/CaptivePortal/logs/omada_webhook_normalized.log",
)
VISIT_LIFECYCLE_SCAN_INTERVAL_SECONDS = os.getenv(
    "VISIT_LIFECYCLE_SCAN_INTERVAL_SECONDS", "5"
)
VISIT_LIFECYCLE_RECONCILE_INTERVAL_SECONDS = os.getenv(
    "VISIT_LIFECYCLE_RECONCILE_INTERVAL_SECONDS", "30"
)
VISIT_LIFECYCLE_MAX_LINE_BYTES = os.getenv(
    "VISIT_LIFECYCLE_MAX_LINE_BYTES", "1048576"
)
VISIT_LIFECYCLE_READER_MAX_LINES_PER_SCAN = os.getenv(
    "VISIT_LIFECYCLE_READER_MAX_LINES_PER_SCAN", "5000"
)
VISIT_LIFECYCLE_READER_MAX_BYTES_PER_SCAN = os.getenv(
    "VISIT_LIFECYCLE_READER_MAX_BYTES_PER_SCAN", "16777216"
)
VISIT_LIFECYCLE_READER_MAX_DURATION_SECONDS = os.getenv(
    "VISIT_LIFECYCLE_READER_MAX_DURATION_SECONDS", "20"
)
VISIT_LIFECYCLE_RECONCILE_BATCH_SIZE = os.getenv(
    "VISIT_LIFECYCLE_RECONCILE_BATCH_SIZE", "500"
)
VISIT_LIFECYCLE_PENDING_OFFLINE_BATCH_SIZE = os.getenv(
    "VISIT_LIFECYCLE_PENDING_OFFLINE_BATCH_SIZE", "500"
)
VISIT_LIFECYCLE_OFFLINE_MATCH_GRACE_SECONDS = os.getenv(
    "VISIT_LIFECYCLE_OFFLINE_MATCH_GRACE_SECONDS", "30"
)
VISIT_LIFECYCLE_START_BUSY_TIMEOUT_MS = os.getenv(
    "VISIT_LIFECYCLE_START_BUSY_TIMEOUT_MS", ""
)
VISIT_LIFECYCLE_START_WRITER_SLOT_WAIT_MS = os.getenv(
    "VISIT_LIFECYCLE_START_WRITER_SLOT_WAIT_MS",
    VISIT_LIFECYCLE_START_BUSY_TIMEOUT_MS or "750",
)
VISIT_LIFECYCLE_READER_WRITER_SLOT_WAIT_MS = os.getenv(
    "VISIT_LIFECYCLE_READER_WRITER_SLOT_WAIT_MS", "250"
)
VISIT_LIFECYCLE_RECONCILIATION_WRITER_SLOT_WAIT_MS = os.getenv(
    "VISIT_LIFECYCLE_RECONCILIATION_WRITER_SLOT_WAIT_MS", "250"
)
VISIT_LIFECYCLE_SQLITE_BUSY_TIMEOUT_MS = os.getenv(
    "VISIT_LIFECYCLE_SQLITE_BUSY_TIMEOUT_MS", "500"
)
VISIT_LIFECYCLE_START_MAX_ATTEMPTS = os.getenv(
    "VISIT_LIFECYCLE_START_MAX_ATTEMPTS", "3"
)
VISIT_LIFECYCLE_START_TOTAL_BUDGET_MS = os.getenv(
    "VISIT_LIFECYCLE_START_TOTAL_BUDGET_MS", "2000"
)
VISIT_LIFECYCLE_SHUTDOWN_TIMEOUT_SECONDS = os.getenv(
    "VISIT_LIFECYCLE_SHUTDOWN_TIMEOUT_SECONDS", "20"
)
VISIT_LIFECYCLE_MAX_OFFLINE_CLOCK_SKEW_SECONDS = os.getenv(
    "VISIT_LIFECYCLE_MAX_OFFLINE_CLOCK_SKEW_SECONDS", "120"
)
VISIT_LIFECYCLE_MAX_REPORTED_DURATION_DRIFT_SECONDS = os.getenv(
    "VISIT_LIFECYCLE_MAX_REPORTED_DURATION_DRIFT_SECONDS", "300"
)

# Observation Storage Foundation (safe disabled default)
OBSERVATION_FOUNDATION_ENABLED = os.getenv(
    "OBSERVATION_FOUNDATION_ENABLED",
    "false",
)
OBSERVATION_DB_PATH = os.getenv(
    "OBSERVATION_DB_PATH",
    "/opt/CaptivePortal/data/observations.sqlite3",
)
OBSERVATION_DYNAMIC_RETENTION_DAYS = os.getenv(
    "OBSERVATION_DYNAMIC_RETENTION_DAYS",
    "180",
)
OBSERVATION_CONFIG_RETENTION_DAYS = os.getenv(
    "OBSERVATION_CONFIG_RETENTION_DAYS",
    "730",
)
OBSERVATION_CLEANUP_INITIAL_DELAY_SECONDS = os.getenv(
    "OBSERVATION_CLEANUP_INITIAL_DELAY_SECONDS",
    "900",
)
OBSERVATION_CLEANUP_INTERVAL_SECONDS = os.getenv(
    "OBSERVATION_CLEANUP_INTERVAL_SECONDS",
    "86400",
)
OBSERVATION_CLEANUP_BATCH_SIZE = os.getenv(
    "OBSERVATION_CLEANUP_BATCH_SIZE",
    "5000",
)
OBSERVATION_CLEANUP_MAX_DURATION_SECONDS = os.getenv(
    "OBSERVATION_CLEANUP_MAX_DURATION_SECONDS",
    "30",
)
OBSERVATION_SHUTDOWN_TIMEOUT_SECONDS = os.getenv(
    "OBSERVATION_SHUTDOWN_TIMEOUT_SECONDS",
    "20",
)
OBSERVATION_CLIENT_ENABLED = os.getenv(
    "OBSERVATION_CLIENT_ENABLED",
    "true",
)
OBSERVATION_SITE_IDS = os.getenv("OBSERVATION_SITE_IDS", "")
OBSERVATION_CLIENT_SSIDS = os.getenv("OBSERVATION_CLIENT_SSIDS", "")
OBSERVATION_CLIENT_INITIAL_DELAY_SECONDS = os.getenv(
    "OBSERVATION_CLIENT_INITIAL_DELAY_SECONDS",
    "15",
)
OBSERVATION_CLIENT_INTERVAL_SECONDS = os.getenv(
    "OBSERVATION_CLIENT_INTERVAL_SECONDS",
    "60",
)
OBSERVATION_REQUEST_TIMEOUT_SECONDS = os.getenv(
    "OBSERVATION_REQUEST_TIMEOUT_SECONDS",
    "5",
)
OBSERVATION_CLIENT_PAGE_SIZE = os.getenv(
    "OBSERVATION_CLIENT_PAGE_SIZE",
    "500",
)
OBSERVATION_CLIENT_MAX_PAGES = os.getenv(
    "OBSERVATION_CLIENT_MAX_PAGES",
    "20",
)
OBSERVATION_CLIENT_MAX_ROWS = os.getenv(
    "OBSERVATION_CLIENT_MAX_ROWS",
    "10000",
)
OBSERVATION_AP_ENABLED = os.getenv("OBSERVATION_AP_ENABLED", "true")
OBSERVATION_AP_INITIAL_DELAY_SECONDS = os.getenv(
    "OBSERVATION_AP_INITIAL_DELAY_SECONDS", "10"
)
OBSERVATION_AP_INTERVAL_SECONDS = os.getenv(
    "OBSERVATION_AP_INTERVAL_SECONDS", "30"
)
OBSERVATION_AP_INVENTORY_INTERVAL_SECONDS = os.getenv(
    "OBSERVATION_AP_INVENTORY_INTERVAL_SECONDS", "300"
)
OBSERVATION_AP_INVENTORY_MAX_STALE_SECONDS = os.getenv(
    "OBSERVATION_AP_INVENTORY_MAX_STALE_SECONDS", "900"
)
OBSERVATION_AP_CONFIG_INTERVAL_SECONDS = os.getenv(
    "OBSERVATION_AP_CONFIG_INTERVAL_SECONDS", "21600"
)
OBSERVATION_AP_PAGE_SIZE = os.getenv("OBSERVATION_AP_PAGE_SIZE", "100")
OBSERVATION_AP_MAX_PAGES = os.getenv("OBSERVATION_AP_MAX_PAGES", "10")
OBSERVATION_AP_MAX_ROWS = os.getenv("OBSERVATION_AP_MAX_ROWS", "500")
OBSERVATION_AP_DYNAMIC_MAX_REQUESTS_PER_CYCLE = os.getenv(
    "OBSERVATION_AP_DYNAMIC_MAX_REQUESTS_PER_CYCLE", "200"
)
OBSERVATION_AP_CONFIG_MAX_REQUESTS_PER_CYCLE = os.getenv(
    "OBSERVATION_AP_CONFIG_MAX_REQUESTS_PER_CYCLE", "200"
)
OBSERVATION_AP_CYCLE_MAX_DURATION_SECONDS = os.getenv(
    "OBSERVATION_AP_CYCLE_MAX_DURATION_SECONDS", "120"
)
OBSERVATION_AP_CONFIG_CYCLE_MAX_DURATION_SECONDS = os.getenv(
    "OBSERVATION_AP_CONFIG_CYCLE_MAX_DURATION_SECONDS", "180"
)
OBSERVATION_RATE_MAX_GAP_SECONDS = os.getenv(
    "OBSERVATION_RATE_MAX_GAP_SECONDS", "180"
)

# Current Network State Foundation (safe disabled default)
CURRENT_STATE_ENABLED = os.getenv("CURRENT_STATE_ENABLED", "false")
CURRENT_STATE_DB_PATH = os.getenv(
    "CURRENT_STATE_DB_PATH", "/opt/CaptivePortal/data/current_state.sqlite3"
)
CURRENT_STATE_SITE_IDS = os.getenv("CURRENT_STATE_SITE_IDS", "")
CURRENT_STATE_CLIENT_SSIDS_JSON = os.getenv(
    "CURRENT_STATE_CLIENT_SSIDS_JSON", "[]"
)
CURRENT_STATE_CLIENT_INITIAL_DELAY_SECONDS = os.getenv(
    "CURRENT_STATE_CLIENT_INITIAL_DELAY_SECONDS", "10"
)
CURRENT_STATE_CLIENT_INTERVAL_SECONDS = os.getenv(
    "CURRENT_STATE_CLIENT_INTERVAL_SECONDS", "60"
)
CURRENT_STATE_AP_INITIAL_DELAY_SECONDS = os.getenv(
    "CURRENT_STATE_AP_INITIAL_DELAY_SECONDS", "15"
)
CURRENT_STATE_AP_INTERVAL_SECONDS = os.getenv(
    "CURRENT_STATE_AP_INTERVAL_SECONDS", "60"
)
CURRENT_STATE_REQUEST_TIMEOUT_SECONDS = os.getenv(
    "CURRENT_STATE_REQUEST_TIMEOUT_SECONDS", "5"
)
CURRENT_STATE_CLIENT_PAGE_SIZE = os.getenv("CURRENT_STATE_CLIENT_PAGE_SIZE", "500")
CURRENT_STATE_CLIENT_MAX_PAGES = os.getenv("CURRENT_STATE_CLIENT_MAX_PAGES", "20")
CURRENT_STATE_CLIENT_MAX_ROWS = os.getenv("CURRENT_STATE_CLIENT_MAX_ROWS", "10000")
CURRENT_STATE_AP_PAGE_SIZE = os.getenv("CURRENT_STATE_AP_PAGE_SIZE", "100")
CURRENT_STATE_AP_MAX_PAGES = os.getenv("CURRENT_STATE_AP_MAX_PAGES", "10")
CURRENT_STATE_AP_MAX_ROWS = os.getenv("CURRENT_STATE_AP_MAX_ROWS", "500")
CURRENT_STATE_CLIENT_FRESH_MAX_AGE_SECONDS = os.getenv(
    "CURRENT_STATE_CLIENT_FRESH_MAX_AGE_SECONDS", "60"
)
CURRENT_STATE_CLIENT_STALE_MAX_AGE_SECONDS = os.getenv(
    "CURRENT_STATE_CLIENT_STALE_MAX_AGE_SECONDS", "180"
)
CURRENT_STATE_AP_FRESH_MAX_AGE_SECONDS = os.getenv(
    "CURRENT_STATE_AP_FRESH_MAX_AGE_SECONDS", "90"
)
CURRENT_STATE_AP_STALE_MAX_AGE_SECONDS = os.getenv(
    "CURRENT_STATE_AP_STALE_MAX_AGE_SECONDS", "300"
)
CURRENT_STATE_HISTORY_RETENTION_HOURS = os.getenv(
    "CURRENT_STATE_HISTORY_RETENTION_HOURS", "48"
)
CURRENT_STATE_HISTORY_MAX_CLIENT_ROWS = os.getenv(
    "CURRENT_STATE_HISTORY_MAX_CLIENT_ROWS", "5000000"
)
CURRENT_STATE_CLEANUP_INITIAL_DELAY_SECONDS = os.getenv(
    "CURRENT_STATE_CLEANUP_INITIAL_DELAY_SECONDS", "300"
)
CURRENT_STATE_CLEANUP_INTERVAL_SECONDS = os.getenv(
    "CURRENT_STATE_CLEANUP_INTERVAL_SECONDS", "3600"
)
CURRENT_STATE_CLEANUP_MAX_CYCLES_PER_RUN = os.getenv(
    "CURRENT_STATE_CLEANUP_MAX_CYCLES_PER_RUN", "100"
)
CURRENT_STATE_CLEANUP_MAX_ROWS_PER_TRANSACTION = os.getenv(
    "CURRENT_STATE_CLEANUP_MAX_ROWS_PER_TRANSACTION", "100000"
)
CURRENT_STATE_CLEANUP_MAX_DURATION_SECONDS = os.getenv(
    "CURRENT_STATE_CLEANUP_MAX_DURATION_SECONDS", "30"
)
CURRENT_STATE_SQLITE_BUSY_TIMEOUT_MS = os.getenv(
    "CURRENT_STATE_SQLITE_BUSY_TIMEOUT_MS", "500"
)
CURRENT_STATE_SHUTDOWN_TIMEOUT_SECONDS = os.getenv(
    "CURRENT_STATE_SHUTDOWN_TIMEOUT_SECONDS", "20"
)

# Analytics Read and Data Quality Foundation and internal read API
ANALYTICS_FOUNDATION_ENABLED = os.getenv(
    "ANALYTICS_FOUNDATION_ENABLED", "false"
)
ANALYTICS_WIRELESS_ENABLED = os.getenv(
    "ANALYTICS_WIRELESS_ENABLED", "true"
)
ANALYTICS_VISIT_ENABLED = os.getenv("ANALYTICS_VISIT_ENABLED", "true")
ANALYTICS_DEFAULT_LIMIT = os.getenv("ANALYTICS_DEFAULT_LIMIT", "500")
ANALYTICS_MAX_LIMIT = os.getenv("ANALYTICS_MAX_LIMIT", "2000")
ANALYTICS_MAX_QUERY_WINDOW_DAYS = os.getenv(
    "ANALYTICS_MAX_QUERY_WINDOW_DAYS", "31"
)
ANALYTICS_MAX_QUERY_DURATION_SECONDS = os.getenv(
    "ANALYTICS_MAX_QUERY_DURATION_SECONDS", "10"
)
ANALYTICS_QUALITY_GAP_THRESHOLD_SECONDS = os.getenv(
    "ANALYTICS_QUALITY_GAP_THRESHOLD_SECONDS", "180"
)
ANALYTICS_WIRELESS_MIN_SAMPLES = os.getenv(
    "ANALYTICS_WIRELESS_MIN_SAMPLES", "20"
)
ANALYTICS_WIRELESS_MAX_WINDOW_DAYS = os.getenv(
    "ANALYTICS_WIRELESS_MAX_WINDOW_DAYS", "7"
)
ANALYTICS_COUNTER_MAX_GAP_SECONDS = os.getenv(
    "ANALYTICS_COUNTER_MAX_GAP_SECONDS", "180"
)
ANALYTICS_AP_JOIN_MAX_LAG_SECONDS = os.getenv(
    "ANALYTICS_AP_JOIN_MAX_LAG_SECONDS", "120"
)
ANALYTICS_RSSI_THRESHOLD_DBM = os.getenv("ANALYTICS_RSSI_THRESHOLD_DBM", "")
ANALYTICS_SNR_THRESHOLD_DB = os.getenv("ANALYTICS_SNR_THRESHOLD_DB", "")
ANALYTICS_VISIT_MIN_COHORT_SIZE = os.getenv(
    "ANALYTICS_VISIT_MIN_COHORT_SIZE", "20"
)
ANALYTICS_VISIT_MAX_WINDOW_DAYS = os.getenv(
    "ANALYTICS_VISIT_MAX_WINDOW_DAYS", "90"
)
ANALYTICS_API_ENABLED = os.getenv("ANALYTICS_API_ENABLED", "false")
ANALYTICS_API_BEARER_TOKEN = os.getenv("ANALYTICS_API_BEARER_TOKEN", "")
ANALYTICS_API_ALLOWED_NETWORKS = os.getenv(
    "ANALYTICS_API_ALLOWED_NETWORKS", "127.0.0.1/32,::1/128"
)
ANALYTICS_API_ALLOWED_SITE_IDS = os.getenv(
    "ANALYTICS_API_ALLOWED_SITE_IDS", ""
)
ANALYTICS_API_MAX_CONCURRENT_REQUESTS = os.getenv(
    "ANALYTICS_API_MAX_CONCURRENT_REQUESTS", "2"
)
ANALYTICS_API_MAX_RESPONSE_BYTES = os.getenv(
    "ANALYTICS_API_MAX_RESPONSE_BYTES", "1048576"
)

# Site-aware read-only Admin Web foundation (safe disabled default)
WEB_ADMIN_ENABLED = os.getenv("WEB_ADMIN_ENABLED", "false")
WEB_ADMIN_USERNAME = os.getenv("WEB_ADMIN_USERNAME", "")
WEB_ADMIN_PASSWORD_HASH = os.getenv("WEB_ADMIN_PASSWORD_HASH", "")
WEB_ADMIN_ALLOWED_NETWORKS = os.getenv(
    "WEB_ADMIN_ALLOWED_NETWORKS", "127.0.0.1/32,::1/128"
)
WEB_ADMIN_ALLOWED_SITE_IDS = os.getenv("WEB_ADMIN_ALLOWED_SITE_IDS", "")
WEB_ADMIN_DEFAULT_SITE_ID = os.getenv("WEB_ADMIN_DEFAULT_SITE_ID", "")
WEB_ADMIN_REQUIRE_HTTPS = os.getenv("WEB_ADMIN_REQUIRE_HTTPS", "true")
WEB_ADMIN_SESSION_IDLE_SECONDS = os.getenv(
    "WEB_ADMIN_SESSION_IDLE_SECONDS", "1800"
)
WEB_ADMIN_SESSION_ABSOLUTE_SECONDS = os.getenv(
    "WEB_ADMIN_SESSION_ABSOLUTE_SECONDS", "28800"
)
WEB_ADMIN_LOGIN_WINDOW_SECONDS = os.getenv(
    "WEB_ADMIN_LOGIN_WINDOW_SECONDS", "300"
)
WEB_ADMIN_LOGIN_MAX_FAILURES = os.getenv(
    "WEB_ADMIN_LOGIN_MAX_FAILURES", "5"
)
WEB_ADMIN_LOGIN_LOCK_SECONDS = os.getenv(
    "WEB_ADMIN_LOGIN_LOCK_SECONDS", "900"
)
WEB_ADMIN_PREAUTH_CSRF_TTL_SECONDS = os.getenv(
    "WEB_ADMIN_PREAUTH_CSRF_TTL_SECONDS", "300"
)
WEB_ADMIN_MAX_PREAUTH_STATES = os.getenv(
    "WEB_ADMIN_MAX_PREAUTH_STATES", "256"
)
WEB_ADMIN_MAX_SESSIONS = os.getenv("WEB_ADMIN_MAX_SESSIONS", "128")
WEB_ADMIN_MAX_LOGIN_TRACKERS = os.getenv(
    "WEB_ADMIN_MAX_LOGIN_TRACKERS", "512"
)
WEB_ADMIN_MAX_POST_BYTES = os.getenv("WEB_ADMIN_MAX_POST_BYTES", "16384")
WEB_ADMIN_MAX_QUERY_STRING_BYTES = os.getenv(
    "WEB_ADMIN_MAX_QUERY_STRING_BYTES", "8192"
)
WEB_ADMIN_MAX_USERNAME_CHARS = os.getenv(
    "WEB_ADMIN_MAX_USERNAME_CHARS", "128"
)
WEB_ADMIN_MAX_PASSWORD_CHARS = os.getenv(
    "WEB_ADMIN_MAX_PASSWORD_CHARS", "1024"
)
WEB_ADMIN_MAX_CSRF_CHARS = os.getenv("WEB_ADMIN_MAX_CSRF_CHARS", "256")
WEB_ADMIN_MAX_NEXT_CHARS = os.getenv("WEB_ADMIN_MAX_NEXT_CHARS", "2048")
WEB_ADMIN_MAX_CURSOR_CHARS = os.getenv(
    "WEB_ADMIN_MAX_CURSOR_CHARS", "4096"
)
WEB_ADMIN_MAX_FILTER_CHARS = os.getenv(
    "WEB_ADMIN_MAX_FILTER_CHARS", "256"
)
WEB_ADMIN_MAX_CONCURRENT_QUERIES = os.getenv(
    "WEB_ADMIN_MAX_CONCURRENT_QUERIES", "2"
)
WEB_ADMIN_MAX_QUERY_DURATION_SECONDS = os.getenv(
    "WEB_ADMIN_MAX_QUERY_DURATION_SECONDS", "10"
)
WEB_ADMIN_MAX_RESPONSE_BYTES = os.getenv(
    "WEB_ADMIN_MAX_RESPONSE_BYTES", "1048576"
)
WEB_ADMIN_DEVICE_PAGE_SIZE = os.getenv("WEB_ADMIN_DEVICE_PAGE_SIZE", "100")
WEB_ADMIN_VISIT_PAGE_SIZE = os.getenv("WEB_ADMIN_VISIT_PAGE_SIZE", "100")
WEB_ADMIN_OBSERVATION_PAGE_SIZE = os.getenv(
    "WEB_ADMIN_OBSERVATION_PAGE_SIZE", "100"
)
WEB_ADMIN_OBSERVATION_MAX_WINDOW_HOURS = os.getenv(
    "WEB_ADMIN_OBSERVATION_MAX_WINDOW_HOURS", "24"
)

# RFC 8908/8910 CAPPORT
CAPPORT_ENABLED = True
CAPPORT_SITE_ID = "6a64f17630da7c70d232187a"
CAPPORT_PUBLIC_BASE_URL = "https://captivportal-navi.duckdns.org"
CAPPORT_API_PATH = "/capport/api"
CAPPORT_LOGIN_PATH = "/capport/login"
CAPPORT_ALLOWED_CLIENT_NETWORKS = (
    "192.168.1.0/24",
    "192.168.8.0/22",
)
CAPPORT_CLIENT_CACHE_TTL_SECONDS = 2
CAPPORT_FAILURE_CACHE_TTL_SECONDS = 2

# Omada webhook receiver
OMADA_WEBHOOK_ENABLED = os.getenv(
    "OMADA_WEBHOOK_ENABLED",
    "false",
)
OMADA_WEBHOOK_ALLOWED_IPS = os.getenv(
    "OMADA_WEBHOOK_ALLOWED_IPS",
    "",
)
OMADA_WEBHOOK_AUTH_MODE = os.getenv(
    "OMADA_WEBHOOK_AUTH_MODE",
    "ip_only",
)
OMADA_WEBHOOK_SHARED_SECRET = os.getenv(
    "OMADA_WEBHOOK_SHARED_SECRET",
    "",
)
OMADA_WEBHOOK_HEADER_TOKEN = os.getenv(
    "OMADA_WEBHOOK_HEADER_TOKEN",
    "",
)
OMADA_WEBHOOK_MAX_BODY_BYTES = os.getenv(
    "OMADA_WEBHOOK_MAX_BODY_BYTES",
    "1048576",
)
OMADA_WEBHOOK_LOG_FILE = os.getenv(
    "OMADA_WEBHOOK_LOG_FILE",
    "/opt/CaptivePortal/logs/omada_webhook.log",
)
OMADA_WEBHOOK_NORMALIZED_LOG_FILE = os.getenv(
    "OMADA_WEBHOOK_NORMALIZED_LOG_FILE",
    "/opt/CaptivePortal/logs/omada_webhook_normalized.log",
)
OMADA_WEBHOOK_SITE_ID_MAP_JSON = os.getenv(
    "OMADA_WEBHOOK_SITE_ID_MAP_JSON",
    "{}",
)

# Omada OpenAPI settings
OMADA_URL = os.getenv("OMADA_URL", "").strip()
OMADA_ID = os.getenv("OMADA_ID", "").strip()
CLIENT_ID = os.getenv("OMADA_CLIENT_ID", "").strip()
CLIENT_SECRET = os.getenv("OMADA_CLIENT_SECRET", "").strip()

# Pending Session Cleaner defaults (strings / env-driven)
PENDING_SESSION_CLEANER_ENABLED = os.getenv("PENDING_SESSION_CLEANER_ENABLED", "false")
PENDING_SESSION_CLEANER_SSIDS = os.getenv("PENDING_SESSION_CLEANER_SSIDS", "Zefer_Parki")
PENDING_SESSION_CLEANER_INITIAL_DELAY_SECONDS = os.getenv("PENDING_SESSION_CLEANER_INITIAL_DELAY_SECONDS", "10")
PENDING_SESSION_CLEANER_SCAN_INTERVAL_SECONDS = os.getenv("PENDING_SESSION_CLEANER_SCAN_INTERVAL_SECONDS", "60")
PENDING_SESSION_CLEANER_MAX_SCAN_DURATION_SECONDS = os.getenv("PENDING_SESSION_CLEANER_MAX_SCAN_DURATION_SECONDS", "50")
PENDING_SESSION_CLEANER_MIN_UPTIME_SECONDS = os.getenv("PENDING_SESSION_CLEANER_MIN_UPTIME_SECONDS", "120")
PENDING_SESSION_CLEANER_PORTAL_GRACE_SECONDS = os.getenv("PENDING_SESSION_CLEANER_PORTAL_GRACE_SECONDS", "45")
PENDING_SESSION_CLEANER_UPTIME_REGRESSION_TOLERANCE_SECONDS = os.getenv("PENDING_SESSION_CLEANER_UPTIME_REGRESSION_TOLERANCE_SECONDS", "5")
PENDING_SESSION_CLEANER_REQUEST_TIMEOUT_SECONDS = os.getenv("PENDING_SESSION_CLEANER_REQUEST_TIMEOUT_SECONDS", "5")
PENDING_SESSION_CLEANER_GET_RETRY_DELAYS_SECONDS = os.getenv("PENDING_SESSION_CLEANER_GET_RETRY_DELAYS_SECONDS", "1,3")
PENDING_SESSION_CLEANER_VERIFY_DELAYS_SECONDS = os.getenv("PENDING_SESSION_CLEANER_VERIFY_DELAYS_SECONDS", "1,4")
PENDING_SESSION_CLEANER_PAGE_SIZE = os.getenv("PENDING_SESSION_CLEANER_PAGE_SIZE", "500")
PENDING_SESSION_CLEANER_MAX_PAGES = os.getenv("PENDING_SESSION_CLEANER_MAX_PAGES", "20")
PENDING_SESSION_CLEANER_MAX_CLIENTS = os.getenv("PENDING_SESSION_CLEANER_MAX_CLIENTS", "10000")
PENDING_SESSION_CLEANER_MAX_ACTIONS_PER_SCAN = os.getenv("PENDING_SESSION_CLEANER_MAX_ACTIONS_PER_SCAN", "1")
PENDING_SESSION_CLEANER_ACTION_COOLDOWN_SECONDS = os.getenv("PENDING_SESSION_CLEANER_ACTION_COOLDOWN_SECONDS", "180")
PENDING_SESSION_CLEANER_MAX_ACTIONS_PER_MAC_PER_HOUR = os.getenv("PENDING_SESSION_CLEANER_MAX_ACTIONS_PER_MAC_PER_HOUR", "3")
PENDING_SESSION_CLEANER_LOG_FILE = os.getenv("PENDING_SESSION_CLEANER_LOG_FILE", "/opt/CaptivePortal/logs/pending_session_cleaner.log")
PENDING_SESSION_CLEANER_ROTATION_MAX_BYTES = os.getenv("PENDING_SESSION_CLEANER_ROTATION_MAX_BYTES", "52428800")
PENDING_SESSION_CLEANER_ROTATION_BACKUP_COUNT = os.getenv("PENDING_SESSION_CLEANER_ROTATION_BACKUP_COUNT", "20")
PENDING_SESSION_CLEANER_SHUTDOWN_TIMEOUT_SECONDS = os.getenv("PENDING_SESSION_CLEANER_SHUTDOWN_TIMEOUT_SECONDS", "20")
