from __future__ import annotations

from pathlib import Path

from .test_traffic_history_frontend import (
    _foundation_source,
    _node,
    _range_context_source,
    _run_node,
)


ROOT = Path(__file__).parents[2]
SOURCE = ROOT / "app" / "admin_web" / "static" / "admin.js"


def _panel_source() -> str:
    source = SOURCE.read_text(encoding="utf-8")
    return source.split("/* TRAFFIC_HISTORY_PANEL_START */", 1)[1].split(
        "/* TRAFFIC_HISTORY_PANEL_END */", 1
    )[0]


def test_peak_is_passive_and_uses_the_one_combined_history_request():
    panel = _panel_source()
    assert "fetch(" not in panel
    assert "AbortController" not in panel
    assert "setTimeout(" not in panel and "setInterval(" not in panel
    assert "visibilitychange" not in panel and "pagehide" not in panel
    assert '"statistics,peak"' in panel
    assert "encodeURIComponent(include)" in panel
    assert panel.count("registerPanel({") == 1
    assert "innerHTML" not in panel


def test_peak_real_node_dom_combined_fetch_and_local_malformed_isolation(tmp_path):
    harness = r'''
const assert=(value,message)=>{if(!value)throw new Error(message);};
class Element { constructor(id,ns=null){this.id=id;this.namespaceURI=ns;this.dataset={};this.textContent="";this.attributes={};this.children=[];}
  setAttribute(key,value){this.attributes[key]=String(value);} replaceChildren(...children){this.children=children;} }
const ids=["admin-page","traffic-history-panel","traffic-history-state","traffic-history-state-title","traffic-history-state-message","traffic-history-applied-range","traffic-history-coverage","traffic-history-watermark","traffic-history-gaps","traffic-history-source-transitions","traffic-history-timezone","traffic-history-chart-svg",
"traffic-statistics-panel","traffic-statistics-state","traffic-statistics-state-title","traffic-statistics-state-message","traffic-statistics-average-download","traffic-statistics-average-upload","traffic-statistics-average-total","traffic-statistics-peak-download","traffic-statistics-peak-upload","traffic-statistics-peak-total","traffic-statistics-applied-range","traffic-statistics-coverage","traffic-statistics-interval-coverage","traffic-statistics-watermark",
"traffic-peak-panel","traffic-peak-state","traffic-peak-state-title","traffic-peak-state-message","traffic-peak-download","traffic-peak-download-at","traffic-peak-upload","traffic-peak-upload-at","traffic-peak-total","traffic-peak-total-at","traffic-peak-bucket","traffic-peak-bucket-range","traffic-peak-hour","traffic-peak-hour-range","traffic-peak-applied-range","traffic-peak-coverage","traffic-peak-watermark","traffic-peak-source-transitions"];
const elements=Object.fromEntries(ids.map((id)=>[id,new Element(id)]));
elements["admin-page"].dataset={page:"traffic",trafficEnabled:"true"};
elements["traffic-history-panel"].dataset={historyEnabled:"true"};elements["traffic-statistics-panel"].dataset={statisticsEnabled:"true"};elements["traffic-peak-panel"].dataset={peakEnabled:"true"};
elements["traffic-history-chart-svg"].namespaceURI="urn:svg";
let registrations=[];global.window={CaptivPortalTrafficCoordinator:{registerPanel:(spec)=>{registrations.push(spec);return true;},refreshPanel:()=>Promise.resolve(true)},CaptivPortalTrafficNetworkRange:{selected:()=>"24h",subscribe:()=>()=>{}}};
global.document={getElementById:(id)=>elements[id]||null,createElementNS:(ns,name)=>new Element(name,ns)};
const site="0123456789abcdef01234567";
function payload(){const end=Date.parse("2026-08-30T12:00:00.000Z"),start=end-86400000,buckets=[];
 for(let i=0;i<288;i++)buckets.push({bucket_start_utc:new Date(start+i*300000).toISOString(),bucket_end_utc:new Date(start+(i+1)*300000).toISOString(),download_mbps:i===0?0:1.25,upload_mbps:.25,total_mbps:i===0?.25:1.5,status:"complete",selected_source:"wired",selection_reason:"primary_full_coverage",source_changed_from_previous:false,complete_site_sample_count:1,excluded_site_sample_count:0,gap_count_over_threshold:0,selected_source_skew_excluded_sample_count:0});
 const statistics={status:"ok",metric_version:"network_traffic_period_statistics.v1",average_method:"right_endpoint_sample_hold_time_weighted.v1",peak_method:"max_accepted_complete_site_sample.v1",unit:"Mbps",average:{download_mbps:1.25,upload_mbps:.25,total_mbps:1.5},peak:{download_mbps:1.25,upload_mbps:.25,total_mbps:1.5},interval_evidence:{range_seconds:86400,candidate_interval_count:287,accepted_interval_count:287,accepted_interval_seconds:86100,interval_coverage_ratio:86100/86400,excluded_gap_interval_count:0,excluded_source_transition_interval_count:0,invalid_period_interval_count:0,accepted_peak_sample_count:288,leading_unweighted_seconds:0,trailing_unweighted_seconds:300}};
 const peak_load={status:"ok",metric_version:"network_traffic_peak_load.v1",unit:"Mbps",peak_value_method:"max_accepted_complete_site_sample.v1",peak_tie_break_method:"earliest_peak_sample_at.v1",sample_timestamp_semantics:"cycle_finished_at",events:{download:{value_mbps:1.25,sample_at_utc:buckets[1].bucket_start_utc,selected_source:"wired",occurrence_count:287},upload:{value_mbps:.25,sample_at_utc:buckets[0].bucket_start_utc,selected_source:"wired",occurrence_count:288},total:{value_mbps:1.5,sample_at_utc:buckets[1].bucket_start_utc,selected_source:"wired",occurrence_count:287}},busiest_bucket:{status:"ok",bucket_start_utc:buckets[1].bucket_start_utc,bucket_end_utc:buckets[1].bucket_end_utc,average_total_mbps:1.5,selected_source:"wired",occurrence_count:287,method:"max_complete_history_bucket_total_mean.v1",tie_break_method:"earliest_bucket_start.v1"},busiest_hour:{status:"ok",window_start_utc:buckets[0].bucket_start_utc,window_end_utc:buckets[11].bucket_end_utc,duration_seconds:3600,average_total_mbps:1.5,accepted_interval_seconds:3600,selected_source:"wired",method:"max_complete_rolling_3600s_average_total_sample_hold.v1",average_method:"right_endpoint_sample_hold_time_weighted.v1",tie_break_method:"earliest_window_start.v1"}};
 buckets[10].source_changed_from_previous=true;
 return {api_version:"admin.read.v1",site_id:site,result:{status:"ok",range:{id:"24h",from_utc:new Date(start).toISOString(),to_utc:new Date(end).toISOString(),evaluated_at_utc:new Date(end).toISOString(),bucket_seconds:300,bucket_count:288,unit:"Mbps",aggregation:"mean_of_complete_site_rate_samples",metric_version:"network_traffic_history.v1",source_kind:"observation_ap_dynamic",sample_timestamp_semantics:"cycle_finished_at",bucket_alignment:"range_start_utc",max_site_history_buckets:720,max_site_sample_source_skew_seconds:60},buckets,coverage:{status:"complete",available_from_utc:new Date(start).toISOString(),available_through_utc:new Date(end).toISOString(),source_watermark_utc:new Date(end).toISOString(),source_age_seconds:0,bucket_count:288,complete_bucket_count:288,partial_bucket_count:0,missing_bucket_count:0,canonical_cycle_count:288,complete_site_sample_count:288,excluded_site_sample_count:0,gap_bucket_count:0,source_transition_count:1},quality:{},period_statistics:statistics,peak_load}};}
function insufficientPayload(){const value=payload(),result=value.result,seconds=86400;
 result.status="insufficient_data";for(const bucket of result.buckets){bucket.download_mbps=null;bucket.upload_mbps=null;bucket.total_mbps=null;bucket.status="none";bucket.selected_source=null;bucket.selection_reason="no_canonical_samples";bucket.source_changed_from_previous=false;bucket.complete_site_sample_count=0;bucket.gap_count_over_threshold=0;}
 Object.assign(result.coverage,{status:"none",complete_bucket_count:0,partial_bucket_count:0,missing_bucket_count:288,canonical_cycle_count:0,complete_site_sample_count:0,gap_bucket_count:0,source_transition_count:0});
 Object.assign(result.period_statistics,{status:"insufficient_data",average:{download_mbps:null,upload_mbps:null,total_mbps:null},peak:{download_mbps:null,upload_mbps:null,total_mbps:null},interval_evidence:{range_seconds:seconds,candidate_interval_count:0,accepted_interval_count:0,accepted_interval_seconds:0,interval_coverage_ratio:0,excluded_gap_interval_count:0,excluded_source_transition_interval_count:0,invalid_period_interval_count:0,accepted_peak_sample_count:0,leading_unweighted_seconds:seconds,trailing_unweighted_seconds:seconds}});
 result.peak_load={status:"insufficient_data",metric_version:"network_traffic_peak_load.v1",unit:"Mbps",peak_value_method:"max_accepted_complete_site_sample.v1",peak_tie_break_method:"earliest_peak_sample_at.v1",sample_timestamp_semantics:"cycle_finished_at",events:{download:{value_mbps:null,sample_at_utc:null,selected_source:null,occurrence_count:0},upload:{value_mbps:null,sample_at_utc:null,selected_source:null,occurrence_count:0},total:{value_mbps:null,sample_at_utc:null,selected_source:null,occurrence_count:0}},busiest_bucket:{status:"insufficient_data",bucket_start_utc:null,bucket_end_utc:null,average_total_mbps:null,selected_source:null,occurrence_count:0,method:"max_complete_history_bucket_total_mean.v1",tie_break_method:"earliest_bucket_start.v1"},busiest_hour:{status:"insufficient_data",window_start_utc:null,window_end_utc:null,duration_seconds:3600,average_total_mbps:null,accepted_interval_seconds:null,selected_source:null,method:"max_complete_rolling_3600s_average_total_sample_hold.v1",average_method:"right_endpoint_sample_hold_time_weighted.v1",tie_break_method:"earliest_window_start.v1"}};return value;}
'''
    assertions = r'''
(async()=>{assert(registrations.length===1,"one History registration");const spec=registrations[0];let url=null;const first=await spec.load({siteId:site,apiBase:"/api",requestJson:async(value)=>{url=value;return payload();}});assert(url==="/api/traffic/history?range=24h&include=statistics%2Cpeak","one combined Peak request");spec.render(first);assert(elements["traffic-history-state-title"].textContent==="History ready","History rendered");assert(elements["traffic-statistics-state-title"].textContent==="Period statistics ready","Statistics rendered");assert(elements["traffic-peak-state-title"].textContent==="Peak Load ready","Peak rendered");assert(elements["traffic-peak-download"].textContent==="1.25 Mbps","Peak value");assert(elements["traffic-peak-download-at"].textContent.startsWith("Observed at "),"Observed at label");assert(elements["traffic-peak-hour-range"].textContent!=="—","rolling hour rendered");assert(elements["traffic-peak-applied-range"].textContent==="Last 24 hours","applied range visible");assert(elements["traffic-peak-bucket-range"].textContent.includes("First of 287 equal buckets"),"bucket tie note visible");assert(elements["traffic-peak-source-transitions"].textContent==="1","nonzero source transitions visible");
const empty=await spec.load({siteId:site,apiBase:"/api",requestJson:async()=>insufficientPayload()});spec.render(empty);assert(elements["traffic-peak-download"].textContent==="—"&&elements["traffic-peak-download-at"].textContent==="No accepted peak sample","null Peak event explanation");assert(elements["traffic-peak-bucket-range"].textContent==="No complete comparable bucket","bucket insufficient explanation");assert(elements["traffic-peak-hour-range"].textContent==="No complete comparable 60-minute period","hour insufficient explanation");
const bad=payload();bad.result.peak_load.busiest_hour.occurrence_count=1;const isolated=await spec.load({siteId:site,apiBase:"/api",requestJson:async()=>bad});spec.render(isolated);assert(elements["traffic-history-state-title"].textContent==="History ready","malformed Peak keeps History");assert(elements["traffic-statistics-state-title"].textContent==="Period statistics ready","malformed Peak keeps Statistics");assert(elements["traffic-peak-state-title"].textContent==="Peak Load unavailable","malformed Peak stays local");console.log("TRAFFIC_PEAK_OK");})().catch((error)=>{console.error(error);process.exitCode=1;});
'''
    output = _run_node(tmp_path, harness + _panel_source() + assertions)
    assert "TRAFFIC_PEAK_OK" in output


def test_peak_uses_shared_range_generation_without_stale_overwrite(tmp_path):
    harness = r'''
const assert=(value,message)=>{if(!value)throw new Error(message);};
const settle=()=>new Promise((resolve)=>setImmediate(resolve));
class Element{constructor(id,namespaceURI=null){this.id=id;this.namespaceURI=namespaceURI;this.dataset={};this.textContent="";this.hidden=false;this.disabled=false;this.attributes={};this.children=[];this.listeners={};}setAttribute(key,value){this.attributes[key]=String(value);}addEventListener(kind,callback){(this.listeners[kind]??=[]).push(callback);}replaceChildren(...children){this.children=children;}click(){for(const callback of this.listeners.click||[])callback({preventDefault(){}});}}
const ids=["admin-page","refresh-button","traffic-global-state","traffic-global-state-title","traffic-global-state-message","traffic-empty-state","traffic-panels","traffic-history-panel","traffic-history-state","traffic-history-state-title","traffic-history-state-message","traffic-history-applied-range","traffic-history-coverage","traffic-history-watermark","traffic-history-gaps","traffic-history-source-transitions","traffic-history-timezone","traffic-history-chart-svg","traffic-network-range-24h","traffic-network-range-7d","traffic-statistics-panel","traffic-statistics-state","traffic-statistics-state-title","traffic-statistics-state-message","traffic-statistics-average-download","traffic-statistics-average-upload","traffic-statistics-average-total","traffic-statistics-peak-download","traffic-statistics-peak-upload","traffic-statistics-peak-total","traffic-statistics-applied-range","traffic-statistics-coverage","traffic-statistics-interval-coverage","traffic-statistics-watermark","traffic-peak-panel","traffic-peak-state","traffic-peak-state-title","traffic-peak-state-message","traffic-peak-download","traffic-peak-download-at","traffic-peak-upload","traffic-peak-upload-at","traffic-peak-total","traffic-peak-total-at","traffic-peak-bucket","traffic-peak-bucket-range","traffic-peak-hour","traffic-peak-hour-range","traffic-peak-applied-range","traffic-peak-coverage","traffic-peak-watermark","traffic-peak-source-transitions"];
const elements=Object.fromEntries(ids.map((id)=>[id,new Element(id)])),site="0123456789abcdef01234567";elements["traffic-history-chart-svg"].namespaceURI="urn:svg";elements["admin-page"].dataset={page:"traffic",trafficEnabled:"true",siteId:site,apiBase:`/admin/api/v1/sites/${site}`,trafficRefreshSeconds:"60",trafficRequestTimeoutSeconds:"20"};elements["traffic-history-panel"].dataset={historyEnabled:"true"};elements["traffic-statistics-panel"].dataset={statisticsEnabled:"true"};elements["traffic-peak-panel"].dataset={peakEnabled:"true"};
const documentListeners={},windowListeners={};global.document={hidden:false,getElementById:(id)=>elements[id]||null,createElementNS:(ns,name)=>new Element(name,ns),addEventListener:(kind,callback)=>{(documentListeners[kind]??=[]).push(callback);}};let timerId=0;const timers=new Map();global.window={location:{origin:"https://localhost"},setTimeout:(callback,delay)=>{const id=++timerId;timers.set(id,{callback,delay});return id;},clearTimeout:(id)=>timers.delete(id),addEventListener:(kind,callback)=>{(windowListeners[kind]??=[]).push(callback);}};global.performance={now:()=>1000};
function payload(rangeId){const spec=rangeId==="24h"?{seconds:86400,bucket:300,count:288}:{seconds:604800,bucket:900,count:672},end=Date.parse("2026-08-29T12:00:00.000Z"),start=end-spec.seconds*1000,buckets=Array.from({length:spec.count},(_item,index)=>({bucket_start_utc:new Date(start+index*spec.bucket*1000).toISOString(),bucket_end_utc:new Date(start+(index+1)*spec.bucket*1000).toISOString(),download_mbps:1,upload_mbps:0,total_mbps:1,status:"complete",selected_source:"wired",selection_reason:"primary_full_coverage",source_changed_from_previous:false,complete_site_sample_count:1,excluded_site_sample_count:0,gap_count_over_threshold:0,selected_source_skew_excluded_sample_count:0})),from=new Date(start).toISOString(),to=new Date(end).toISOString(),accepted=spec.count-1,seconds=spec.seconds-spec.bucket;
const statistics={status:"ok",metric_version:"network_traffic_period_statistics.v1",average_method:"right_endpoint_sample_hold_time_weighted.v1",peak_method:"max_accepted_complete_site_sample.v1",unit:"Mbps",average:{download_mbps:1,upload_mbps:0,total_mbps:1},peak:{download_mbps:1,upload_mbps:0,total_mbps:1},interval_evidence:{range_seconds:spec.seconds,candidate_interval_count:accepted,accepted_interval_count:accepted,accepted_interval_seconds:seconds,interval_coverage_ratio:seconds/spec.seconds,excluded_gap_interval_count:0,excluded_source_transition_interval_count:0,invalid_period_interval_count:0,accepted_peak_sample_count:spec.count,leading_unweighted_seconds:0,trailing_unweighted_seconds:spec.bucket}};
const event={value_mbps:1,sample_at_utc:from,selected_source:"wired",occurrence_count:spec.count},peak_load={status:"ok",metric_version:"network_traffic_peak_load.v1",unit:"Mbps",peak_value_method:"max_accepted_complete_site_sample.v1",peak_tie_break_method:"earliest_peak_sample_at.v1",sample_timestamp_semantics:"cycle_finished_at",events:{download:event,upload:{...event,value_mbps:0},total:event},busiest_bucket:{status:"ok",bucket_start_utc:buckets[0].bucket_start_utc,bucket_end_utc:buckets[0].bucket_end_utc,average_total_mbps:1,selected_source:"wired",occurrence_count:spec.count,method:"max_complete_history_bucket_total_mean.v1",tie_break_method:"earliest_bucket_start.v1"},busiest_hour:{status:"ok",window_start_utc:from,window_end_utc:new Date(start+3600000).toISOString(),duration_seconds:3600,average_total_mbps:1,accepted_interval_seconds:3600,selected_source:"wired",method:"max_complete_rolling_3600s_average_total_sample_hold.v1",average_method:"right_endpoint_sample_hold_time_weighted.v1",tie_break_method:"earliest_window_start.v1"}};
return{api_version:"admin.read.v1",site_id:site,result:{status:"ok",range:{id:rangeId,from_utc:from,to_utc:to,evaluated_at_utc:to,bucket_seconds:spec.bucket,bucket_count:spec.count,unit:"Mbps",aggregation:"mean_of_complete_site_rate_samples",metric_version:"network_traffic_history.v1",source_kind:"observation_ap_dynamic",sample_timestamp_semantics:"cycle_finished_at",bucket_alignment:"range_start_utc",max_site_history_buckets:720,max_site_sample_source_skew_seconds:60},buckets,coverage:{status:"complete",available_from_utc:from,available_through_utc:to,source_watermark_utc:to,source_age_seconds:0,bucket_count:spec.count,complete_bucket_count:spec.count,partial_bucket_count:0,missing_bucket_count:0,canonical_cycle_count:spec.count,complete_site_sample_count:spec.count,excluded_site_sample_count:0,gap_bucket_count:0,source_transition_count:0},quality:{},period_statistics:statistics,peak_load}};}
const response=(rangeId)=>({ok:true,status:200,headers:{get:()=>null},json:async()=>payload(rangeId)});let calls=[],hold7=false,pending7=null;global.fetch=(url,options)=>{calls.push(url);const rangeId=url.includes("range=7d")?"7d":"24h";if(hold7&&rangeId==="7d")return new Promise((resolve,reject)=>{pending7={resolve,signal:options.signal};options.signal.addEventListener("abort",()=>reject(new Error("aborted")),{once:true});});return Promise.resolve(response(rangeId));};
'''
    assertions = r'''
(async()=>{await settle();await settle();assert(elements["traffic-peak-applied-range"].textContent==="Last 24 hours","initial Peak range");
elements["traffic-network-range-7d"].click();await settle();await settle();assert(elements["traffic-history-applied-range"].textContent==="Last 7 days"&&elements["traffic-statistics-applied-range"].textContent==="Last 7 days"&&elements["traffic-peak-applied-range"].textContent==="Last 7 days","one success applies 7d to all products");
elements["traffic-network-range-24h"].click();await settle();await settle();assert(elements["traffic-peak-applied-range"].textContent==="Last 24 hours","24h restored");
hold7=true;elements["traffic-network-range-7d"].click();await settle();assert(pending7&&!pending7.signal.aborted,"7d in flight");assert(elements["traffic-peak-applied-range"].textContent==="Last 24 hours","old Peak remains labelled 24h during 7d request");
elements["traffic-network-range-24h"].click();await settle();await settle();assert(pending7.signal.aborted,"7d generation aborted");pending7.resolve(response("7d"));await settle();await settle();assert(elements["traffic-peak-applied-range"].textContent==="Last 24 hours","stale 7d cannot overwrite Peak");console.log("TRAFFIC_PEAK_RANGE_OK");})().catch((error)=>{console.error(error);process.exitCode=1;});
'''
    output = _run_node(
        tmp_path,
        harness + _foundation_source() + _range_context_source()
        + _panel_source() + assertions,
    )
    assert "TRAFFIC_PEAK_RANGE_OK" in output


def test_peak_javascript_syntax_is_real_node_checked():
    import subprocess
    completed = subprocess.run([_node(), "--check", str(SOURCE)], cwd=ROOT, capture_output=True, text=True, timeout=30, check=False)
    assert completed.returncode == 0, completed.stderr
